document.querySelector('button').addEventListener('click', horoscope)

function horoscope(){
    let day = document.querySelector('#dayInput').value;
    let month = document.querySelector('#monthInput').value;


    if (month == 1 && day >= 20 && day <= 31 || month == 2 && day > 0 && day <= 18) {
        document.querySelector('h3').innerText = 'Aquarius - Prometheus'
        document.querySelector('h2').innerText = 'Aquarius has many similarities with Prometheus, the Titan god of forethought and clever counsel who was given the important task of molding mankind out of clay. However, one day Prometheus tricked the gods out of the best portion of the sacrificial meal, taking the meat for the feasting of man. As a punishment for his rebellious act, the king of gods, Zeus, ordered the creation of Pandora, the first woman, in order to deliver misfortune into the house of man. Meanwhile, Prometheus was bound to a stake on Mount Kaukasos where an eagle was set to feed upon his liver for years until Herakles finally came along and released the Titan from his agony. Prometheus shares a lot of similarities with the Aquarian temperament. Aquarius is a humanitarian who is not afraid to stand up for human rights, as Prometheus also loved man more than the Olympian gods. Prometheus refused to support the monarchy and was a rebel and a trickster, much like the inventive Aquarius who rebels against authority and enjoys breaking the rules.'
        document.querySelector('.signPic').src = 'prometheus.jpeg'

    } else if (month == 2 && day >= 19 && day <= 29 || month == 3 && day > 0 && day <= 20){
        document.querySelector('h3').innerText = 'Pisces - Poseidon'
        document.querySelector('h2').innerText = 'Pisces is associated with one of the strongest gods of Olympus, Poseidon, for obvious reasons. He was the god of sea, earthquakes, floods, drought, and horses. Poseidon was the son of Kronos and Rhea, and he was usually portrayed as a mature man with a muscular body and dark beard, holding a trident which was a three-pronged fisherman’s spear. As the ruler of the sea, Poseidon was the protector of all waters and sailors, but he was also worshipped as a fertility god. Poseidon was moody and unstable by nature, and Pisces who feel more than anyone else can also be somewhat moody and unstable at times. Those born under the sign of Pisces are very sensitive, highly intuitive, and can become easily overloaded by crowds. That is why they’re sometimes so eager to go to a place where they can sit alone in peace. Much like dreamy Pisces, Poseidon was a very unpredictable god and when angry, he was able to destroy everything that comes in his way.'
        document.querySelector('.signPic').src = 'poseidon.jpeg'

    } else if (month == 3 && day >= 21 && day <= 31 || month == 4 && day > 0 && day <=19){
        document.querySelector('h3').innerText = 'Aries - Ares'
        document.querySelector('h2').innerText = 'The first sign of the zodiac, Aries is ruled by the planet Mars. Ancient Greeks were amazed by the red color of this planet and they attributed it to Ares, the child of Zeus and Hera, and the God of war. Ares represents masculine fire energy and competition, just like Aries who is also fiery and very competitive. Ares was the son of two of the most powerful gods in Greek mythology, but he did not get along well with either parent. He was known for his chaotic, impulsive behavior, and his tactless aggression. These characteristics are often attributed to those born under the sign of Aries. These individuals are leaders who need mental stimulation to feel happy and fulfilled. Maybe they don’t have a lot of friends, but the ones they do have think of them as their closest companion. Aries people may be impulsive and stubborn, but they’re also fiercely loyal, caring, and bold. They always fight for what they love and they’re not afraid of challenges; that’s why they’re able to achieve whatever they set their minds to.'
        document.querySelector('.signPic').src = 'ares.jpeg'

    } else if (month == 4 && day >= 20 && day <= 30 || month == 5 && day > 0 && day <=20){
        document.querySelector('h3').innerText = 'Taurus - Hestia'
        document.querySelector('h2').innerText = 'If your zodiac sign is Taurus, you’re associated with Hestia, the virgin goddess of the hearth and the home. She was responsible for the cooking of bread and the preparation of family meals. Hestia was the first child of Kronos and Rhea, and she was also the goddess of the sacrificial flame and received a portion of every sacrifice to the gods. Taurus relates to Hestia in several ways: people born under this sign are caring, dedicated, patient, supportive, and loyal just like this goddess who is often depicted as a veiled woman holding a flowering branch. Much like the goddess of heat and family life, Taureans exemplify what it means to be a good and caring friend. Family is their biggest priority; they’re very protective of their family members and friends, and are always deeply involved in household matters. These people never miss important family events like anniversaries and they remember everyone’s birthdays.'
        document.querySelector('.signPic').src = 'hestia.jpeg'

    } else if (month == 5 && day >= 21 && day <= 31 || month == 6 && day > 0 && day <=20){
        document.querySelector('h3').innerText = 'Gemini - Hermes'
        document.querySelector('h2').innerText = 'The third sign of the zodiac, Gemini is ruled by the planet Mercury. Mercury is actually named after Hermes, the winged-helmeted messenger of the gods who moved quickly across the sky at the command of other gods. Hermes was also the god of herds and flocks, of communication, language, and writing, and that’s why he is usually associated with social and talkative Gemini. Hermes was the herald and the personal messenger of the powerful Zeus, but he was also the guide of the dead and he led souls down into the underworld. Geminis are witty, intelligent, resourceful, charming, and versatile much like Hermes. On the flip side, they can also be two-faced, judgmental, and restless. They have an insatiable thirst for knowledge and a very lively imagination which makes them one of the most creative zodiac signs. They’re quick-witted and thanks to their gift of gab, they can talk their way out of everything.'
        document.querySelector('.signPic').src = 'hermes.jpeg'

    } else if (month == 6 && day >= 21 && day <= 30 || month == 7 && day > 0 && day <= 22){
        document.querySelector('h3').innerText = 'Cancer - Artemis'
        document.querySelector('h2').innerText = 'Cancer is often associated with one of the fiercest, most widely respected Olympian goddesses, Artemis. She was the goddess of Moon, the ruling planet of Cancer, but was also known as the goddess of hunting, wilderness, childbirth, virginity, and as a protectress of young girls. In Greek mythology, Artemis was usually portrayed as a young maiden with a hunting bow and arrows. She was a virgin and afraid of men, that is why she used to live in the woods and only went for walks at night. Artemis is similar to people born under the sign of Cancer, who are also very modest, shy, extremely emotional individuals who love children and their home. Those born under this zodiac sign are kind, calm, maternal, compassionate, dedicated, rough and yet nurturing at the same time. They’re fiercely loyal and protective of their home and family, so anyone who messes with their loved ones will certainly feel their wrath.'
        document.querySelector('.signPic').src = 'artemis.jpeg'

    } else if (month == 7 && day >= 23 && day <= 31 || month == 8 && day > 0 && day <= 22){
        document.querySelector('h3').innerText = 'Leo - Zeus'
        document.querySelector('h2').innerText = 'Leo is Zeus, the almighty; the strongest and most powerful Greek god. Zeus was the king of gods and the god of the sky, weather, destiny, fate, kingship, law, and order. Zeus was the youngest son of the Titans Kronos and Rhea. He married his sister, goddess of the sky Hera, and they had three children - Ares, Hebe, and Eileithyia. However, Zeus also had many affairs with various women, so he was also the father of many mortal heroes including Herakles, Helen of Troy, and Perseus. Zeus was always depicted as a regal, majestic and mature man with an athletic body, dark beard, wreath of olive-leaves and a lightning bolt in his hands. Zeus was a carefree and unpredictable god who loved to laugh out loud. He was known as a wise, fair, and merciful god, but he was also easily angered. These characteristics are also attributed to people born under the sign of Leo. Leos are proud, self-centered, and a little arrogant, but at the same time very wise, generous, and fair just like the king of gods Zeus.'
        document.querySelector('.signPic').src = 'zeus.jpeg'

    } else if (month == 8 && day >= 23 && day <= 31 || month == 9 && day > 0 && day <=22){
        document.querySelector('h3').innerText = 'Virgo - Demeter'
        document.querySelector('h2').innerText = 'Virgo is connected to Demeter, the goddess of agriculture, grain, and bread. In astrology, Virgo is often depicted as a woman carrying grain, just like Demeter, the goddess of the harvest and one of the most powerful figures in Greek mythology. Demeter was the daughter of Kronos and Rhea, and is usually portrayed as a mature woman, wearing a crown and bearing sheaves of wheat and a torch. Demeter’s name literally translates as “Mother Earth”. She was seen as a mother figure and a caretaker because she was very involved in the growth and harvest of the food from the Earth. Demeter is related to people born under the sign of Virgo who are also resourceful, hardworking, clever, and helpful. On the flip side, they can be preachy, critical, anxious, and extremely observant, but they’ll always be there to help out a friend in need.'
        document.querySelector('.signPic').src = 'demeter.jpeg'

    } else if (month == 9 && day >=23 && day <= 30 || month == 10 && day > 0 && day <=22){
        document.querySelector('h3').innerText = 'Libra - Aphrodite'
        document.querySelector('h2').innerText = 'Those born under the sign of Libra are ruled by the planet Venus which is associated with Aphrodite, who was the goddess of love, pleasure, beauty, and procreation. She was portrayed as a beautiful woman accompanied by the winged and mischievous god of love, Eros. Many gods believed that Aphrodite’s beauty and charm could spark a war of the gods. Because of that, Zeus married Aphrodite to Hephaestus, the god of blacksmiths who was very ugly and deformed. However, despite her marriage to Hephaestus, Aphrodite had many lovers, both gods and men. Libras are charming, lovable, romantic, graceful, compassionate and fair, much like Aphrodite. This goddess was known to be quite vain which is also one of Libra’s worst traits. Even though these people are lovable and charming, they also have trouble finding the right companion in life, just like the goddess of beauty.'
        document.querySelector('.signPic').src = 'aphrodite.jpeg'

    } else if (month == 10 && day >= 23 && day <= 31 || month == 11 && day > 0 && day <= 21){
        document.querySelector('h3').innerText = 'Scorpio - Hades'
        document.querySelector('h2').innerText = 'Scorpio is associated with Hades (Haides), the god of the dead and the king of the underworld. Scorpio is very mysterious, powerful, seductive, and the most misunderstood sign of the zodiac. Hades was also known as evil and mysterious, which is a huge misunderstanding because he was only the ruler of the underworld. He was often misunderstood just like Scorpio, and was the only god who never cheated on his bride, showing loyalty and commitment, which are some of well known Scorpio traits. Hades was responsible for the funeral rites and defended the right of the dead people. In Greek mythology, he was always shown as a regal god with a dark beard. Just like Scorpio, Hades was intense, trustworthy, passionate, and caring, but he was also extremely protective, possessive and had no mercy for those who tried to hurt his loved ones.'
        document.querySelector('.signPic').src = 'hades.jpeg'

    } else if (month == 11 && day >= 22 && day <= 30 || month == 12 && day > 0 && day <=21){
        document.querySelector('h3').innerText = 'Sagittarius - Dionysus'
        document.querySelector('h2').innerText = 'Sagittarius relates directly to Dionysus, the god of wine, pleasure, vegetation, festivity, and madness. Dionysus was the son of Zeus and the princess Semele of Thebes. He was often depicted either as a feminine, long-haired young man or an old man with beard. His accessories included a drinking cup, a crown of ivy, and thyrsos; a staff of giant fennel covered with ivy vines and leaves. Much like Dionysus, Sagittarians are enthusiastic, optimistic, honest, wise, philosophical, but they’re also reckless, tactless individuals with an insatiable thirst for adventure. Sagittarians are some of the funniest and most entertaining people of the zodiac, and that is why they usually have a lot of friends. These people are explorers and risk-takers just like the god of wine, and even though they can be loyal and monogamous, Sagittarius is widely known as the “bachelor” sign.'
        document.querySelector('.signPic').src = 'dionysus.jpeg'

    } else if (month == 12 && day >= 22 && day <= 31 || month == 1 && day > 0 && day <= 19){
        document.querySelector('h3').innerText = 'Capricorn - Apollo'
        document.querySelector('h2').innerText = 'Capricorn is a zodiac sign that relates to Apollo in several ways. Apollo was the god of music, song, poetry, prophecy, archery, healing, and the protection of the young. He was the son of Zeus and Leto and he was portrayed as a handsome and beardless young man with a wreath and branch of laurel, bow and arrows, a raven, and a lyre. Capricorn is also a very skilled, artistic, determined, and hardworking sign with a never-ending desire to achieve their goals and dreams. These people often have a talent for making music or writing, much like Apollo. They are the “popular” people of the zodiac who enjoy spending quality time with family and friends or working on huge projects. Capricorns are very ambitious and always have their eyes on the prize, so friends who can help them increase their status are very valuable assets.'
        document.querySelector('.signPic').src = 'apollo.jpeg'

    }   else {
        document.querySelector('h2').innerText = "Enter Valid Date Values";
    }
}